# Uncomment the next line to define a global platform for your project
 platform :ios, '10.0'

target 'Phonercise' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Phonercise
  pod 'ThreeRingControl', :git => 'https://github.com/hellowupeng/ThreeRingControl', :tag => '1.0.0'

  target 'PhonerciseTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
